### ISSUE TITLE
Using it for realtime timeseries, the memory exploded to 2GB

### ISSUE THREAD

**Issue by perkasajob** [plotly/react-plotly.js#104]
I am wondering, whether it can be used for realtime timeseries chart ?

**Comment by nicolaskruchten** [comment]
Can you tell us a bit more about your use case? How often were you adding
points? We’re you removing points as well from the beginning of the series?
Many traces did you have? Etc

**Comment by perkasajob** [comment]
My setup using redux-saga, dva js to be precise, the data coming in every seconds, following is the reducer:
```
setRtData2(state, action) {
        if(state.rtData.length >1000)
            state.rtData.shift()
        return {
          ...state,
          rtData: [...state.rtData, action.payload],
        };
 },
```
and render is following : 
```
<Plot
   data={[
   {    x: rtData?rtData.x:[],
        y: rtData?rtDatay.y:[],
        type: 'scatter',
        mode: 'lines+points',
        marker: {color: '#19d3f3'},
        name: 'M1',
    },]}
/>
```
test using 1000 points, 2 lines (result in 2000 points) in a plot, yes, I did shift array after 1000 points
I tried to use ringjs as ring buffer, but it did not help either.
I am aware react store previous state, to detect changes, is it possible, all the state history piling up to drive memory out of control ?
any other information required ?

**Comment by perkasajob** [comment]
a false alarm, it seems the complex of redux,  somewhere has caused memory leak, disassembled to the bones, problem disappeared, thank you for attention.

**Comment by nicolaskruchten** [comment]
Ok, glad it worked out!
