### ISSUE TITLE
Rangeslider functionality in react-plotly.js

### ISSUE THREAD

**Issue by SaloniDesai** [plotly/react-plotly.js#106]
Does react-plotly.js currently supports range slider functionality that plotly.js has ?
https://codepen.io/plotly/pen/WwXEoV
I would like to implement a time-series range slider just like this example: https://plot.ly/javascript/range-slider/#basic-range-slider-on-time-series

Will react-plotly.js allow me to do so ? If not, is there any plan to add it ?

**Comment by nicolaskruchten** [comment]
Yes: any plotly.js figure can be rendered in through react-plotly.js.
