### ISSUE TITLE
downloadImage / toImage using react component <Plot/>

### ISSUE THREAD

**Issue by florianrf** [plotly/react-plotly.js#107]
Hi, I am using React component <Plot/> and I need to use the functionalities of downloadImage or toImage to either automatically save plots as images or use the related urls. 

My idea is to use graphDiv from the onInitialized prop and to pass it to downloadImage / toImage but in both cases I get this error:
Error while plotting: TypeError: Object(...) is not a function
    at onInitialized
   at PlotlyComponent.figureCallback

Is there another way to go to automatically save plots as images?

Here is my code:
<Plot
                    data={this.state.data}
                    layout={this.state.layout}
                    onInitialized={(figure, graphDiv) => {
                        downloadImage(graphDiv, {format: 'png', filename: 'newplot'});
                        toImage(graphDiv, {format: 'png'}).then((url) => {
                           this.setState({figure: figure, url: url});
                        });
                        }}
 />

Thank you!

**Comment by pmalde** [comment]
Hi Florian,

Did you manage to solve this? If so could you please share?

Thanks

**Comment by gwsampso** [comment]
+1 for this... @florianrf  @pmalde  any success?
