### ISSUE TITLE
Getting error only in production 

### ISSUE THREAD

**Issue by Elavazhuthi** [plotly/react-plotly.js#109]
hello team.
getting the below error while plotting the graph. any reason why we are seeing this error.	
description"Object doesn't support property or method 'remove'"
number-2146827850
stack"TypeError: Object doesn't support property or method 'remove'

this seems to be working when running app locally.

**Comment by Elavazhuthi** [comment]
Getting error at this block call at c.deleteRelatedStyleRule

**Comment by nicolaskruchten** [comment]
This seems like it's due to https://github.com/plotly/plotly.js/issues/3186 which will likely be fixed in a patch release shortly.

**Comment by antoinerg** [comment]
Fixed since plotly.js [v1.42.1](https://github.com/plotly/plotly.js/releases/tag/v1.42.1). The patch can be found at the following link https://github.com/plotly/plotly.js/pull/3187.
