### ISSUE TITLE
window.URL.createObjectURL jest fail

### ISSUE THREAD

**Issue by juliehubs** [plotly/react-plotly.js#115]
When running a jest test, you will receive an error that window.URL.createObjectURL is not a function.

Any ideas of a way to fix this?

I have tried mocking it in jest, as I have found that this is supposedly a mapbox issue, but none of those solutions seem to work.

**Comment by GamalielCrdz** [comment]
the same here.
![image](https://user-images.githubusercontent.com/26840574/50183013-89d1dd80-02d6-11e9-8fbd-dc6ef325e8f0.png)

**Comment by antoinerg** [comment]
Thank you for reporting this issue.

@juliehubs You're right that the problem lies in mapbox. Did you try mocking the function as suggested in the following comment https://github.com/mapbox/mapbox-gl-js/issues/3436#issuecomment-421117409?

**Comment by juliehubs** [comment]
@antoinerg  I tried addign that in  my test, didn't seem to work, but I am probably doing something wrong to be honest.

**Comment by GamalielCrdz** [comment]
> Thank you for reporting this issue.
> 
> @juliehubs You're right that the problem lies in mapbox. Did you try mocking the function as suggested in the following comment [mapbox/mapbox-gl-js#3436 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/3436#issuecomment-421117409)?

I added to my test and also install jest-canvas-mock, this works form me

**Comment by juliehubs** [comment]
What am I doing wrong?! I feel so confused! @GamalielCrdz 

`window.URL.createObjectURL = function() {};
configure({ adapter: new Adapter(), });

test('renders plotly', () => {
    const wrapper = shallow(
        <MyChart/>
    );

    expect(wrapper).toMatchSnapshot();
    expect(wrapper.state().data).toEqual(null);
});`

**Comment by GamalielCrdz** [comment]
> What am I doing wrong?! I feel so confused! @GamalielCrdz
> 
> ```
> window.URL.createObjectURL = function() {};
> configure({ adapter: new Adapter(), });
> 
> test('renders plotly', () => {
>     const wrapper = shallow(
>         <MyChart/>
>     );
>     expect(wrapper).toMatchSnapshot();
>     expect(wrapper.state().data).toEqual(null);
> });
> ```

@juliehubs in my case, I added the follow line
`window.URL.createObjectURL = function() {};`
in my setupTest.js file

**Comment by juliehubs** [comment]
> @juliehubs in my case, I added the follow line
> `window.URL.createObjectURL = function() {};`
> in my setupTest.js file

That did it! Thanks so much!

**Comment by antoinerg** [comment]
Thank you @GamalielCrdz!

**Comment by ped59430** [comment]
Still getting an error after applying the 2 tips above, any idea ?
(Using vue jest but seems related)

![image](https://user-images.githubusercontent.com/9555650/71523610-18a20e80-28ca-11ea-9774-5780f4c914ef.png)

**Comment by ped59430** [comment]
All precisions here https://github.com/hustcc/jest-canvas-mock/issues/2

The tests are passing, but the error is logged due to a jsdom peculiarity on the `getContext` function.

As I do not need to test `getContext` and want a clean console (as mentioned in this comment https://github.com/hustcc/jest-canvas-mock/issues/2#issuecomment-464690381), I added this line `window.HTMLCanvasElement.prototype.getContext = () => {}` to my `jest.setup.js` file.

**Comment by enua** [comment]
> @juliehubs in my case, I added the follow line
> `window.URL.createObjectURL = function() {};`
> in my setupTest.js file

If you come here from **Vue**, I solve this from your solution doing this:

`window.URL.createObjectURL = jest.fn();`

Hope to helps someone.
