### ISSUE TITLE
Radar not displaying correctly

### ISSUE THREAD

**Issue by mooncitizen** [plotly/react-plotly.js#117]
Using the below does not produce a valid radar chart, see image beneath code, We have tried everything for last couple of days! 

Is there something we are missing?

Also we all other charts are working fine so it isn't a problem with the setup.

```
import React from 'react';
import PropTypes from 'prop-types';
import createPlotlyComponent from 'react-plotly.js/factory';
import _Plot from 'plotly.js/dist/plotly-cartesian';

const Plot = createPlotlyComponent(_Plot);

const RadarChart = ({ data, layout }) => (
  <Plot
    data={[
      {
        type: 'scatterpolar',
        r: [39, 28, 8, 7, 28, 39],
        theta: ['A', 'B', 'C', 'D', 'E', 'A'],
        fill: 'toself',
        name: 'Group A',
      },
      {
        type: 'scatterpolar',
        r: [1.5, 10, 39, 31, 15, 1.5],
        theta: ['A', 'B', 'C', 'D', 'E', 'A'],
        fill: 'toself',
        name: 'Group B',
      },
    ]}
    layout={layout}
  />
);

export const radarChartProps = {
  data: PropTypes.arrayOf(PropTypes.array).isRequired,
  layout: PropTypes.object,
};

RadarChart.defaultProps = {
  layout: {
    polar: {
      radialaxis: {
        visible: true,
        range: [0, 50],
      },
    },
    showlegend: false,
  },
};

RadarChart.propTypes = radarChartProps;

export default RadarChart;
```

![image](https://user-images.githubusercontent.com/45096572/51116961-60886c80-1804-11e9-82bd-7d053852ff41.png)

**Comment by nicolaskruchten** [comment]
What's in `layout`? It looks like the angular axis isn't being set to `categorical` type.

**Comment by mooncitizen** [comment]
```RadarChart.defaultProps = {
  layout: {
    polar: {
      radialaxis: {
        visible: true,
        range: [0, 50],
      },
    },
    showlegend: false,
  },
};```

this default prop works as can show and hide labels

**Comment by etpinard** [comment]
Works ok in pure plotly.js https://codepen.io/etpinard/pen/aPXozx?editors=1010

The image above look a lot like our old (aka legacy) polar charts. @mooncitizen which version of plotly.js are you using?

**Comment by mooncitizen** [comment]
plotly.js version is 1.42.5

**Comment by mooncitizen** [comment]
just updated to latest. still no joy!

**Comment by nicolaskruchten** [comment]
Can you provide a running example like a CodePen or something that we can look at please?

**Comment by mooncitizen** [comment]
@nicolaskruchten Hi, thanks for your support here but we actually found the issue we used the import below which got _Plot from plotly.js/dist/plotly-cartesian. When we rebuilt using plotly.js (see code example below) it resolved the issue. However nothing was wrong our end the documentation or code in here "broke" the radar. I leave a code sample incase anyone else in the future runs into this.

``` import React from 'react';
import PropTypes from 'prop-types';
import createPlotlyComponent from 'react-plotly.js/factory';
import _Plot from 'plotly.js/dist/plotly-cartesian';

import Plotly from 'plotly.js';

const Plot = createPlotlyComponent(Plotly);

const RadarChart = ({ data, layout }) => <Plot data={data} layout={layout} />;

export const radarChartProps = {
  data: PropTypes.arrayOf(PropTypes.array).isRequired,
  layout: PropTypes.object,
};

RadarChart.defaultProps = {
  layout: {
    polar: {
      radialaxis: {
        visible: false,
        range: [0, 50],
      },
    },
    showlegend: false,
  },
};

RadarChart.propTypes = radarChartProps;

export default RadarChart;

**Comment by nicolaskruchten** [comment]
Ah interesting. @etpinard is the old polar loaded in the cartesian bundle?

**Comment by etpinard** [comment]
> is the old polar loaded in the cartesian bundle?

yes.

**Comment by nicolaskruchten** [comment]
OK then, that explains it!
