### ISSUE TITLE
Latest version 2.2.0 incompatible with latest plotly.js

### ISSUE THREAD

**Issue by hydrosquall** [plotly/react-plotly.js#121]
If you use the latest versions of plot.js, react-plotly is unable to find the plotly module. This leads to the following compile-time error:

```
ModuleNotFoundError
Could not find module in path: 'plotly.js/dist/plotly' relative to '/node_modules/react-plotly.js/react-plotly.js'
```

Breaking example (with 2.2.0, and latest plotly.js of 1.44.1)

- https://codesandbox.io/s/lx39zx3m4q

```json
"dependencies": {
    "plotly.js": "1.44.1",
    "react": "16.5.2",
    "react-dom": "16.5.2",
    "react-plotly.js": "2.2.0",
    "react-scripts": "2.0.3"
  },
```

The issue goes away when an old version of react-plotly is used (I used the version in the [demo app](https://github.com/plotly/react-plotly.js-demo-app) since that seems to be the last known version that works.

- https://codesandbox.io/s/1yj0vk1jq4

From package.json
```json
"dependencies": {
    "plotly.js": "1.40.0",
    "react": "16.5.2",
    "react-dom": "16.5.2",
    "react-plotly.js": "1.0.4",
    "react-scripts": "2.0.3"
  },
```

**Comment by alexcjohnson** [comment]
AFAICT this works if I run the identical build locally. I'm not really sure how codesandbox manages dependencies, but the issue seems to be with codesandbox and react-plotly.js v1.7.0+ where we import the pre-built distribution rather than the main entry point. https://github.com/plotly/react-plotly.js/pull/56/files

Codesandbox works with the latest versions using a `<script>` tag and `createPlotlyComponent`
https://codesandbox.io/s/lyv3l6kkwq

**Comment by hydrosquall** [comment]
Hi @alexcjohnson,

Thanks for looking into this and providing the workaround of using `createPlotlyComponent`. I looked at the pen you shared (https://codesandbox.io/s/lyv3l6kkwq)- in fact it still works without using the "script" tag, using the `createPlotlyComponent` technique, since it includes an NPM install of `plotly.js` (example: https://codesandbox.io/s/3848v890lq ).

Given that this is the current situation, if someone follows the `quick start` section of the README.md and doesn't know to pin to an old version of `react-plotly.js`, they'll get the latest version of `react-plotly.js` and `plotly.js`. Would it make sense to update the `README.md` for the quickstart, or to change the behavior of the library so that the library looks where the dist files are now? (I don't have a preference either way)

For what it's worth, I tried running the broken pen's files locally and got the same error as was listed in the codesandbox so I don't think the issue was unique to that particular cloud IDE, but it's moot now that I have a workaround. Thanks for your help!

**Comment by hydrosquall** [comment]
To wrap-up, I ended up using this code snippet, which let me avoid using a script tag.

```js
import createPlotlyComponent from "react-plotly.js/factory";
import Plotly from "plotly.js";

const Plot = createPlotlyComponent(Plotly);
```
