### ISSUE TITLE
Hover event

### ISSUE THREAD

**Issue by sumantka** [plotly/react-plotly.js#131]
We have in our package.json:  "plotly.js": "^1.44.4" and "react": "16.4.2"
We're using plotly like so:
```
const Plotly = require('plotly.js/lib/core');
const createPlotlyComponent = require('react-plotly.js/factory');

// Add more modules as needed
Plotly.register([
  require('plotly.js/lib/scatter'),
  require('plotly.js/lib/table'),
  require('plotly.js/lib/bar'),
]);

module.exports = createPlotlyComponent(Plotly);
```
and using this default export reference as `Plot` in our react component but unfortunately when I use onHover event no event is emitted. Any ideas as to what we're missing would be great. Thanks

**Comment by nicolaskruchten** [comment]
Sorry to get back to you so late: did you resolve this? If not, can you provide a CodePen or some executable example I can look at?

**Comment by sumantka** [comment]
figured it out, nvm, thanks
