### ISSUE TITLE
Broken link to Plotly website

### ISSUE THREAD

**Issue by jbampton** [plotly/react-plotly.js#137]
The link -> `https://plot.ly/products/javascript/` at the top of this repository is broken.

![plotly-broken-link](https://user-images.githubusercontent.com/418747/56457720-f3b3de00-63c1-11e9-83c5-e7253a7869d3.png)

**Comment by jbampton** [comment]
Hey @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Fixed, thanks!
