### ISSUE TITLE
3D Scatter Plot - marker->line->width attribute is broken

### ISSUE THREAD

**Issue by islanddove** [plotly/react-plotly.js#138]
Working with 3D scatter plots, I discovered that changing the marker line width attribute for 3D scatter plots doesn't seem to do anything. It always is sticking with the default.

The only other reference to this bug that I could find is [here](https://community.plot.ly/t/scatter-3d-marker-line-width-only-affects-to-legend/14378). 

I reproduced this bug with [this jsfiddle](https://jsfiddle.net/dolsen1993/oczLs7qj/).

**Comment by nicolaskruchten** [comment]
Thanks for reporting this! I've moved it over to https://github.com/plotly/plotly.js/issues/3807
