### ISSUE TITLE
Cannot read property '_rehover'

### ISSUE THREAD

**Issue by gonzofish** [plotly/react-plotly.js#140]
I'm leveraging react-plotly for a project and getting the following error, 

```console
Error while plotting: TypeError: Cannot read property '_rehover' of undefined
    at push../node_modules/plotly.js/src/plots/plots.js.plots.rehover (plots.js:2814)
    at Object.push../node_modules/plotly.js/src/lib/index.js.lib.syncOrAsync (index.js:413)
    at continueAsync (index.js:408)
```

That line of code is:

```javascript
plots.rehover = function (gd) {
  if (gd._fullLayout._rehover) {
    gd._fullLayout._rehover();
  }
};
```

I'm not sure if this is a react-plotly.js or regular plotly.js issue, since the code it's erroring on is regular plotly.js code. It seems that `plots.rehover` is being called after the plot has been unmounted (that is `purge` has already been called).

Am I doing something wrong?

**Comment by nicolaskruchten** [comment]
@etpinard any thoughts here?

**Comment by etpinard** [comment]
I'm not sure how this can happen (a reproducible example could help :smirk: ), but it would be easy to add an additional safe-guard in `rehover`:

```js
plots.rehover = function (gd) {
  var fullLayout = gd._fullLayout;
  if(fullLayout && fullLayout._rehover) {
    fullLayout._rehover();
  }
};
```

**Comment by gonzofish** [comment]
that'd be great @etpinard! i tried to track it down, but ended up getting very lost in the codebase since i don't really know it

**Comment by etpinard** [comment]
> that'd be great

What would be even _better_ is to provide us a reproducible example :smile:

**Comment by gonzofish** [comment]
Of course 🤦‍♂️ I can try to do that! The current UI I'm writing is slightly complicated in terms of Plotly usage.

I've got 2 graphs that are getting purged/unmounted and then a new one gets mounted after those two are unmounted at a different route. I'll try to create something as simple as I can.

**Comment by gonzofish** [comment]
So I built up a whole code sandbox and cannot get this to reproduce, but I have been able to reproduce it. Like I said, the code around this isn't simple, so I'm sure my sandbox is missing something the real code has.

I think I've tracked it down to a server request pulling data which, in turn, is causing some funkiness with props updating and causing a re-render. I'm still investigating though.

**Comment by gonzofish** [comment]
Ok, so it absolutely (as per usual) was my code causing this to happen, so it might not be worth the effort.

In my code an async request to the server updates a Redux state which updates a parent component of my react-plotly component. At the same time, though, it starts unmounting everything to change pages, so as plotly is trying to re-render, I'm destroying everything. I suppose by the time the `_rehover` function tries to be executed (as a result of the re-render), Plotly has probably purged the graph div of all its Plotly attributes (as a result of the unmounting).
