### ISSUE TITLE
xaxis.range keeps changing when using drag zoom

### ISSUE THREAD

**Issue by mbkupfer** [plotly/react-plotly.js#141]
Zoom interaction changes the xaxis that is in my state. Why is this happening and how do I mitigate? Specifically, it changes autorange to false and updates the xaxis range to the previous zoom level, even when I manually set those to `true` and `[-0.5, 21.5]`, respectively.

Below are all obtained from JSON.stringify(this.state.layout), which must confirm that the plot is updating the xaxis without me setting anything. This even happens when I don't include: `onUpdate={(figure) => this.setState(figure)}` in my Plot component which is even more of a head scratcher. 

## layout.xaxis at initial component state
```
"xaxis": {
    "visible": true,
    "autorange": true,
    "type": "category",
    "range": [
      -0.5,
      21.5
    ]
  },
```
## layout.xaxis after zoom event
`autorange` somehow gets set to `false` and range gets set to zoomed range. I guess it makes sense for this to occur on a zoom event, but how does it update state? 

```
"xaxis": {
    "visible": true,
    "autorange": false,
    "type": "category",
    "range": [
      9.912621359223301,
      17.067961165048544
    ]
  },
```
## layout.xaxis after removing all data when react-select is cleared

```
"xaxis": {
    "visible": false,
    "autorange": true,
    "type": "category",
    "range": [
      -0.5,
      21.5
    ],
  },

```

This all happens in an onChange event for my react-select dropdown. I set the state using immutability-helper, and it looks fine because it is exactly what I set it to.
```
const layout = selection.length === 0  ?  { ...EmptyLayout }  :  { ...BASE_LAYOUT }
this.setState(prevState => {

// logic to figure out what dropdown ui event was triggered, 
// and below is the return if it was a clear event

return update(prevState, {
                    selectedSegment: { $set: selection },
                    data: { $set: [] },
                    layout: { $set: layout },
                    config: { $merge: staticPlot }
                })
```
where EmptyLayout is set to:
```
xaxis: {
        visible: false,
        autorange: true,
        type: 'category',
        range: [-0.5, 21.5],
    },
```

## layout.xaxis after adding a selection in react-select dropdown. 
And then this is where my logic of how react completely breaks down and my brain begins to implode...why does this change the range to what I had before and why does it set `autorange` to `false`!? 

```
"xaxis": {
    "visible": true,
    "autorange": false,
    "type": "category",
    "range": [
      9.912621359223301,
      17.067961165048544
    ]
  },
```

**Comment by nicolaskruchten** [comment]
> Why is this happening and how do I mitigate? 

This is a documented behaviour which is a known divergence from the usual React way of doing things... (see the "warning" here https://github.com/plotly/react-plotly.js#api-reference)

There is no way to prevent it from happening, as this is how plotly.js works internally unfortunately.

**Comment by mbkupfer** [comment]
I figured out how to get this working. This probably comes down to a combination of a unique use case of changing layouts for different options and the cumbersome process of simultaneously setting multiple nested properties in reacts state. Using uirevision with ramda clone came to the rescue here. 

> This is a documented behaviour which is a known divergence from the usual React way of doing things... (see the "warning" here https://github.com/plotly/react-plotly.js#api-reference)

Yes I read through the react-docs several times and I still couldn't understand, but this makes sense now that I see it is happening under the hood and not through and `setStates()`.

**Comment by nicolaskruchten** [comment]
OK, I'm glad you got it working!
