### ISSUE TITLE
displayModeBar ?

### ISSUE THREAD

**Issue by SirCameron** [plotly/react-plotly.js#142]
Hi Guys

Thanks for this tool.
I saw in plotly.js, one can hide the modebar with the above key..
How is this used in a React context?

Thanks

**Comment by nicolaskruchten** [comment]
You can pass in a `config` object to the `config` prop :)

**Comment by SirCameron** [comment]
Thanks, @nicolaskruchten !

**Comment by nirjack** [comment]
> You can pass in a `config` object to the `config` prop :)

Still not working

below is the code:
<Plotly data={this.state.data} update={this.update} 
          config={{displayModeBar: true}}
          />
Can you guys help?

**Comment by kjprice** [comment]
Unrelated but I found this page trying to see how to remove specific buttons from the mode bar. The following worked for me

```
<Plot
  config={{ modeBarButtonsToRemove: ['toImage'] }}
/>
```

The list of button names that can be removed can be found here: https://plotly.com/javascript/configuration-options/#remove-modebar-buttons

**Comment by ba5eem** [comment]
@kjprice - I also saw that in the docs, but it didn't work for me. In the meantime I did this to hide the png button:
`let pngButton = document.getElementsByClassName('modebar-btn')[0];
...
pngButton.style.visibility = 'hidden';
`
However I did also see in the docs you can customize icons and actions, so I am hoping to figure out the right way to do this. I was thinking that could it be that I am importing the lib like this:
`import createPlotlyComponent from 'react-plotly.js/factory';
const Plot = createPlotlyComponent(Plotly);
`
do I possibly lose the config option?

thanks

**Comment by itschrislow** [comment]
> > You can pass in a `config` object to the `config` prop :)
> 
> Still not working
> 
> below is the code: <Plotly data={this.state.data} update={this.update} config={{displayModeBar: false}} /> Can you guys help?

I'm using TypeScript and extended the interface for Plotly.js. This is what worked for me:

```typescript
declare module 'react-plotly.js' {
  import * as Plotly from 'plotly.js';
  import {PureComponent} from 'react';

  export interface PlotParams {
      // make config a partial
      config?: Partial<Plotly.Config>;
      data: Plotly.PlotData[];
      layout: Partial<Plotly.Layout>;
      // other missing or extended props
  }

  export default class Plot extends PureComponent<PlotParams> {}
}
```
