### ISSUE TITLE
displayModeBar not working

### ISSUE THREAD

**Issue by nirjack** [plotly/react-plotly.js#146]
> You can pass in a `config` object to the `config` prop :)

Still not working

below is the code:
<Plotly data={this.state.data} update={this.update} 
          config={{displayModeBar: false}}
          />
Can you guys help?

_Originally posted by @nirjack in https://github.com/plotly/react-plotly.js/issues/142#issuecomment-496500142_

**Comment by nicolaskruchten** [comment]
This is working for me... can you provide a CodePen or something where this doesn't work?

**Comment by nirjack** [comment]
@nicolaskruchten, 
Please check the below expo snack
https://snack.expo.io/SJvgvrAaV

**Comment by nicolaskruchten** [comment]
So the config part looks correct but the rest of it doesn't... looks like you're setting `data` to something of the shape `{data, layout}` which isn't quite right.

**Comment by nirjack** [comment]
Got the issue, I'm trying this out in react native and I found out that plotly is not supported in react native yet. The library I was using is only using the basic plotly version and hence the config is not working as intended. 
So any idea when this will be available in react native?

**Comment by nicolaskruchten** [comment]
Ah yeah that might be your issue. React-native support is not a priority for us at this time but if it is for your organization, we do accept sponsorships. https://plot.ly/products/consulting-and-oem/

**Comment by nirjack** [comment]
Sure thanks
