### ISSUE TITLE
Disable popup message "Double-click on legend to isolate one trace"

### ISSUE THREAD

**Issue by janosh** [plotly/react-plotly.js#159]
Is there a way to disable the popup "Double-click on legend to isolate one trace" that appears when first clicking on a trace in a plot legend?

![popup](https://user-images.githubusercontent.com/30958850/64422381-dc893a80-d09b-11e9-8306-6aba660f2b9b.png)

**Comment by etpinard** [comment]
This can be done using the [`showTips`](https://github.com/plotly/plotly.js/blob/b45304597ff639c7b9e38adf6a6b48efc47455af/src/plot_api/plot_config.js#L204-L211) config option

Example: https://codepen.io/etpinard/pen/RwbxYNL

**Comment by janosh** [comment]
Nice, that works! Thanks for the quick reply!

**Comment by JovanaIlic** [comment]
Is it possible to disable all popup messages on all actions? For example when downloading a screenshot to png image?

**Comment by wbharding** [comment]
If, like me, anyone is trying to figure out where "showTips" is located among Plotly React options, it seems to be in the `config` property.
