### ISSUE TITLE
Windrose Initial Render and orientation updates failing

### ISSUE THREAD

**Issue by eric-orozco** [plotly/react-plotly.js#164]
Hello,

First, I'm having issues when creating a windrose, the windrose remains hidden behind a layer with CSS class ".main-svg" .  I would expect that the windrose should show without having to manually hide this layer first.

Second, when updating the layout, the windrose is orientation is not updated accordingly whereas updating the title works as expected.  The expected behavior in my case would be that the change to the orientation and revision in the layout would trigger a rotation of the windrose itself.

code sample:
[codesandbox](https://codesandbox.io/s/react-plotly-windrose-5wz7t?fontsize=14)

Regards,
Eric

**Comment by alexcjohnson** [comment]
Weird, that should work, and it does work (at least the first part, haven't looked at the second...) if I replicate it in plain plotly.js in a [codepen](https://codepen.io/alexcjohnson/pen/qBBXYpd?editors=1010) - @etpinard any idea why the react-plotly.js version is making an unused pair of cartesian axes?

Regardless, even if we fix this bug, the `area` trace type is old and no longer being extended. Much better to migrate to the newer `barpolar` trace type https://plot.ly/javascript/wind-rose-charts/

**Comment by nicolaskruchten** [comment]
Heh so that link includes a CodePen which uses `area`! @Mahdis-z can you please sync up the CodePen with the correct `barpolar` code ?

**Comment by eric-orozco** [comment]
The [codesandbox](https://codesandbox.io/s/react-plotly-windrose-5wz7t?fontsize=14) has been updated with the `barpolar` type data and layout. This has resolved the initial render issue.

The orientation remains unchanged after state change.

**Comment by eric-orozco** [comment]
This orientation issue was resolved by using different properties and the linked code sandbox.
