### ISSUE TITLE
Cant install the package 

### ISSUE THREAD

**Issue by tximpa91** [plotly/react-plotly.js#174]
Whenever i try to install this package the NPM throw me this error.

npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
npm WARN notice [SECURITY] static-eval has the following vulnerabilities: 2 moderate. Go here for more details: https://www.npmjs.com/advisories?search=static-eval&version=0.2.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! code E404
npm ERR! 404 Not Found: 3d-view@^2.0.0

**Comment by etpinard** [comment]
Essentially a duplicate of https://github.com/plotly/plotly.js/issues/4576

This is an npm registry problem tracked in https://status.npmjs.org/incidents/lvgmcrfvrvsh

**Comment by etpinard** [comment]
npm has fixed this issue. Closing 

See https://github.com/plotly/plotly.js/issues/4576 for more details.
