### ISSUE TITLE
Hello, may I use this library in a production environment with peace of mind?

### ISSUE THREAD

**Issue by Gzbox** [plotly/react-plotly.js#179]
Hello, would you like to ask is this library still in normal and frequent maintenance? Can I use it in a production environment with peace of mind? (Seeing the latest submission of commit was six months ago, the reliance on the plotly.js has also fallen behind several versions)

**Comment by alexcjohnson** [comment]
Hi @Gzbox - This library is a fairly thin wrapper that only depends on the highest level of the plotly.js API, which hasn't changed in a very long time - hence the reliance only on v1.34+ of plotly.js when we're all the way up to v1.53 now. So from that standpoint it should be just fine.

That said, we're no longer using this package for any Plotly internal purposes AFAIK - our three main consumers of plotly.js - Dash, plotly.py, and Chart Studio - all have their own interfaces to it. So we're not actively extending this package at this point, but we're still watching it for major issues, and we would happily help if anyone submits a PR to improve it.

**Comment by nicolaskruchten** [comment]
Sorry to contradict @alexcjohnson here but actually this library is in production use in Chart Studio and jupyterlab-chart-editor; we regularly integrate it with recent versions of Plotly.js and it works very well :)

**Comment by nicolaskruchten** [comment]
I should add that everything Alex said above is correct: the reason this library sees few commits is that it's extremely stable, not that it's been abandoned ;)

**Comment by Gzbox** [comment]
@nicolaskruchten @alexcjohnson Thank you very much for your answers, I can use it with confidence
