### ISSUE TITLE
Handling state change in component using react-plotly <Plot>

### ISSUE THREAD

**Issue by mhoffman** [plotly/react-plotly.js#18]
Are state multiples changes supported in combination with `onClick` events? Here is an example of what I intend to do https://codepen.io/mjhoffmann/pen/qVVEaZ .

1. Steps to reproduce issue
    Click on one bar, then click on another bar

1. What I would except to happen
    The caption "Selected ..." should change on every click

1. What happens instead
    The caption changes only on the first click but not on any further events.

Is this supported? What is the right way to implement this. Many thanks.

**Comment by bpostlethwaite** [comment]
Thank you for your report and codepen. It's a bug! I'll update this issue once fixed and published.

---
The bug stems from the fact that this module is running on top of `Plotly.newPlot` which runs a `purge` routine on every invocation. `purge` wipes the event listeners from `plotly.js` but `react-plotly.js` does not likewise clear its references. `react-plotly.js` assumes the handlers are still in place and so does not update them.

The fix will be to clear `react-plotly.js` handlers on every `Plotly.newPlot` invocation so it will know to re-register them.

**Comment by mhoffman** [comment]
Thanks for the quick reply. I very much like the fact that you are supporting React.

**Comment by bpostlethwaite** [comment]
published @1.0.4 https://www.npmjs.com/package/react-plotly.js
