### ISSUE TITLE
Add tooltip while Hover in the legend

### ISSUE THREAD

**Issue by rullymartanto** [plotly/react-plotly.js#181]
there is a way to show tooltip when hover in the legend ?

**Comment by CarlosMarioV** [comment]
Hi there! 
Can we add a tooltip in the legend in this 2023?

**Comment by alexcjohnson** [comment]
This package does nothing but wrap plotly.js - here's the same request over there: https://github.com/plotly/plotly.js/issues/5798 - so I'll close this one.
