### ISSUE TITLE
Too many active WebGL contexts. Oldest context will be lost. 

### ISSUE THREAD

**Issue by bidva** [plotly/react-plotly.js#191]
react-plotly.js: "^2.4.0"
chrome : Version 83.0.4103.116 (Official Build) (64-bit)

I'm using the map on the list to render ~13 plots and get this warning on Chrome browser 

by playing with zooming it will render the plot but another plot will be broken by sad Icon not sure if it's related to the warning message or not.
![image](https://user-images.githubusercontent.com/8351624/86497389-66467a80-bd36-11ea-8d50-eb417a7ddbd4.png)

```
list.map((item)=><Plot
          useResizeHandler
          onRelayout={onLayoutChange}
          onClick={onClick}
          onLegendClick={onLegendClick}
          onLegendDoubleClick={onLegendDoubleClick}
          style={{ width: '100%', height: '100%' }}
          layout={_.cloneDeep(plotProps.layout)}
          config={{
            displaylogo: false,
            scrollZoom: true,
            modeBarButtonsToRemove: ['sendDataToCloud'],
          }}
        />)
```

**Comment by bidva** [comment]
Hey @VeraZab, Sorry to pull you up here just want to check if this project is abandoned or not?

**Comment by chriddyp** [comment]
@bidva - This project is not abandoned, it's just stable.

The underlying issue here is in plotly.js, which is the JavaScript graphing library that `react-plotly.js` uses. This issue has been reported there: https://github.com/plotly/plotly.js/issues/2333
