### ISSUE TITLE
Subplots

### ISSUE THREAD

**Issue by xxBingoBongoxx** [plotly/react-plotly.js#204]
Hello, is there a way to make subplots through this lib ? If so, can you give an example on how ?

**Comment by nicolaskruchten** [comment]
Yes: https://plotly.com/python/subplots/

**Comment by nicolaskruchten** [comment]
Ah, sorry, mental wires crossed, I thought this issue was in our Python repo :) Here is the Javascript link: https://plotly.com/javascript/subplots/

**Comment by geoguide** [comment]
But that's not this library?

**Comment by alexcjohnson** [comment]
This repo is a very lightweight React wrapper around [plotly.js](https://github.com/plotly/plotly.js)
The "Python repo" [plotly.py](https://github.com/plotly/plotly.py) is a Python client for plotly.js.
