### ISSUE TITLE
How to draw vertical and horizontal lines?

### ISSUE THREAD

**Issue by wwjd1234** [plotly/react-plotly.js#212]
Is there a way to draw a vertical line and a horizontal line on the plot?

**Comment by batearedcollie** [comment]
I am quite new to Plotly, so others feel free to chip in. But what I do is just add it as an extra data series, something like this.
```
data=[{
	x: [xval,xval],
	y: [ymin, ymax],
	type:"scatter",
	mode:"lines+markers",
}]
```
But I'll admit this is probably not the most elegant solution.

**Comment by alexcjohnson** [comment]
Assuming you want a line that always spans the plot regardless of how you zoom in, the best way to do this is with `layout.shapes` using `xref='paper', yref='y'` (for a horizontal line) or `xref='x', yref='paper'` (for vertical)

Here's an example with rectangles but lines are similar: https://plotly.com/javascript/shapes/#highlighting-time-series-regions-with-rectangle-shapes

**Comment by alexcjohnson** [comment]
Closing, as this won't result in new code - if you have other questions like this the best place to ask is https://community.plotly.com
