### ISSUE TITLE
Does React Dash support Canvas to draw 2D plot?

### ISSUE THREAD

**Issue by zxqcreations** [plotly/react-plotly.js#217]
## What problem I met
Hi, I am trying to integrate this awesome project into my React APP, aimed at a 2D line chart, but my data amount is pretty large -about 100K points- so that the dash draws slow and furthermore, it blocks my WebView, 

## What's my analyzation
Based on the background I mentioned above, I guess this problem can be solved if I use Canvas as the backend of the \<Plot\/\> component.

## What's my question
So is it possible to change the backend of \<Plot\/\> component from SVG to Canvas in React to draw a 2D plot?
Meanwhile, if I want to implement a 3D chart in React, what should I do because I didn't find a component that indicates a 3D plot in react-plotly.js?

## Additionally
Thanks for your awesome work on Dash and please **DO TAKE GOOD CARE** of yourselves, make sure you all are healthy.

**Comment by nicolaskruchten** [comment]
Thanks for the well-wishes!

This library does support line charts and 3d charts up to 100k+ points, if you use the `scattergl` or `scatter3d` trace types.

**Comment by zxqcreations** [comment]
> Thanks for the well-wishes!
> 
> This library does support line charts and 3d charts up to 100k+ points, if you use the `scattergl` or `scatter3d` trace types.

Ah~ It is so easy and so powerful. Thank you so much, I should read the documents more carefully. 
I will close the issue, thank you.
