### ISSUE TITLE
Request for plotly_webglcontextlost event handler

### ISSUE THREAD

**Issue by markovist** [plotly/react-plotly.js#220]
I make use of WebGL graphs and will sometimes lose the context when interacting with them heavily (i.e. making multiple large scattergl selections consecutively).

It would be very useful to have a handler for the [plotly_webglcontextlost](https://plotly.com/javascript/plotlyjs-events/#webgl-context-lost-event) event so that users can choose to handle these errors gracefully and redraw their graphs if necessary. It appears to be a fairly straightforward addition.

**Comment by dmt0** [comment]
@markovist you're welcome to submit a PR :)
You can check the last 2-3 PRs that were merged for a template.
