### ISSUE TITLE
Having trouble with the layout object properties

### ISSUE THREAD

**Issue by bitshiftnetau** [plotly/react-plotly.js#223]
I'm having a slight issue with some of the layout properties, I'm wondering if access to those properties in plotly has been implemented in the wrapper, or if there is something else happening that I'm not quite understanding, 

Basically I want to have the main grid size independent of the data points entered. 

From reading the manual [https://plotly.com/javascript/reference/layout/xaxis/#layout-xaxis-range](here), it says I can do achieve that effect. 

Here is my code:
```

      <Plot
        data={[
          {
            x: [1, 2, 3, 4],
            y: [1, 2, 3],
            z: [1, 2, 3],
            type: 'scatter3d',
            mode: 'lines+markers',
            marker: {color: 'red', symbol: 'circle'},
          },
          {
            x: [1, 2, 3, 4],
            y: [1, 2, 3],
            z: [1, 2, 3],
            type: 'scatter3d',
            mode: 'lines+markers',
            marker: {color: 'blue', symbol: 'circle'},
          }
        ]}
        layout={{width: 1280, height: 720, 
            title: 'A Fancy Plot', 
            xaxis: {
              visible: false,
              type: "log",
              autorange: false,
              rangemode: "nonnegative", 
              range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
            },
            yaxis: {
              type: "log",
              autorange: false,
              rangemode: "nonnegative", 
              range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
            }

          }}
      />

Here is what my screen looks like and doesn't change with the layout properties above

![plot](https://user-images.githubusercontent.com/26871600/102161014-a790a800-3eda-11eb-930f-7593d5d8716e.PNG)

```

**Comment by alexcjohnson** [comment]
Two things going on here:
1. `layout.xaxis` and `layout.yaxis` are for 2D traces. For 3D you want `layout.scene.xaxis` and `layout.scene.yaxis`.
2. `range` is a length-2 array `[min, max]` - looks like a longer array is completely ignored.

I'm going to close this issue as it won't lead to code changes - for usage questions like this a better forum is https://community.plotly.com/c/api/plotly-js/6

**Comment by bitshiftnetau** [comment]
Perfect. Thanks @alexcjohnson I'll use the forums in future.
