### ISSUE TITLE
Ticks disappear when updating width or height

### ISSUE THREAD

**Issue by rgosse** [plotly/react-plotly.js#224]
See this [codesandbox](https://codesandbox.io/s/flamboyant-violet-dbn1l?file=/src/App.js)

When I click on one of the buttons to resize the grid, I trigger a rerender of the plot. The changes are reflected but it has the side effect of making the ticks on the x-axis disappear.

![plotresize](https://user-images.githubusercontent.com/2352621/102406223-450dd980-3fb8-11eb-9628-23eb6a7e84ba.gif)

I created this issue here because I could not reproduce solely using `plotly.js`, see my attempt [here](https://codesandbox.io/s/epic-star-81fvy?file=/src/index.js).

Interestingly, adding `key={Math.random()}` fixes the issue 💩 

Thanks

**Comment by alexcjohnson** [comment]
This looks like https://github.com/plotly/plotly.js/pull/5345 which will be included in the next release.

**Comment by rgosse** [comment]
> This looks like [plotly/plotly.js#5345](https://github.com/plotly/plotly.js/pull/5345) which will be included in the next release.

I tried using the build from this PR in my codepen and indeed it solves the issue. I will try in my project too and confirm.

**Comment by rgosse** [comment]
Closing this issue as `1.58.3` resolves it.
