### ISSUE TITLE
Typescript issues + Is this actually still alive?

### ISSUE THREAD

**Issue by paillave** [plotly/react-plotly.js#229]
I faced many issues that are already mentioned on the list of issues. Not to say that I can't have even have the project working with typescript.
My main question here is: is this project actually still alive? No issue seems to have any answer from anybody, since 2 years. And source code is nearly not touched since 2 years as well. 
I'm asking this because a component with no community behind is just a no-go for my project.

**Comment by nicolaskruchten** [comment]
This project is certainly alive and used in production systems such as https://chart-studio.plotly.com/. We do not use TypeScript ourselves, so we don't put any effort into maintaining any kind of TypeScript bindings or integrations or type definitions. The reason the code hasn't changed much is that it's a very stable wrapper around Plotly.js and our production systems have used it as-is for years. We merge community pull requests when they make sense, though, so feel free to contribute any changes you find necessary for your project :)

**Comment by paillave** [comment]
Ok, that's what I thought. It is clear now. But still, without typescript, I can't succeed to have it working in a create react app.
I am considering writing a 100% typescript conversion of your react-pivottable project. 
But it won't include plotly graphics renderers as I can't possible have the energy to convert your visualizations.

**Comment by nicolaskruchten** [comment]
Sounds like fun! `react-pivottable` initially started out as `PivotTable.js`, which is written in CoffeeScript/jQuery, and I ended up "ejecting" out of CS into ES6/React... The wheels of technology keep grinding along ;)

**Comment by smith558** [comment]
@nicolaskruchten is it still the case the package is maintained?

**Comment by alexcjohnson** [comment]
Yes, in fact there's work going on RN in https://github.com/plotly/react-plotly.js/pull/333 - which should also address the original question in this issue re: TypeScript.
