### ISSUE TITLE
Multiple y axis are not showing up when adding them to the Layout prop

### ISSUE THREAD

**Issue by ANewModern** [plotly/react-plotly.js#232]
When attempting to add multiple y-axes as is shown on the [Plotly documentation](https://plotly.com/javascript/multiple-axes/). Only one axis is appearing. 

This is what I am sending to the layout prop.
```
{ 
  borderRadius: "8px"
  height: 200
  width: 100
  yaxis1: {
    anchor: "x"
    autorange: true
    overlaying: "y"
    position: 0
    range: (2) [-69.4, 319.4]
    side: "left"
    title: {text: "F"}
    type: "linear"
  }
  yaxis2: {
    anchor: "x"
    autorange: true 
    overlaying: "y"
    position: 0.15
    range: (2) [0, 100]
    side: "left"
    title: {text: "%"}
    type: "linear"
  }
}
```
The data being sent to the charts is also within the specified ranges and is rendering on the chart, but they are placed within the range of the first y-axis. 

Is there support for multiple y-axes on react plotly?

**Comment by viltohmyst** [comment]
Hi @ANewModern I'm facing the same issue, was this resolved for you?
