### ISSUE TITLE
Expose Plotly.restyle

### ISSUE THREAD

**Issue by bradpe** [plotly/react-plotly.js#25]
Exposing restyle allows for updating styles on the chart without having to update all of the data.

ie. change the color or size of a marker when clicked.

**Comment by nicolaskruchten** [comment]
See #2 for followup on `Plotly.react`

**Comment by nicolaskruchten** [comment]
Good news! The Plotly.react method is implemented in [plotly.js version 1.34.0](https://github.com/plotly/plotly.js/releases/tag/v1.34.0) and this React wrapper already takes advantage of it, so just upgrade plotly.js and things should be more reactive!

This should address most or all cases where `restyle` or `relayout` would have been useful, although I'd love to know if this doesn't meet your needs.
