### ISSUE TITLE
react-plotly does not work with webpack

### ISSUE THREAD

**Issue by KIC** [plotly/react-plotly.js#27]
in my package.json
```
  "dependencies": {
    "ify-loader": "^1.1.0",
    "mobx": "^3.0.0",
    "mobx-react": "^4.1.0",
    "mobx-react-devtools": "^4.2.11",
    "plotly.js": "^1.31.2",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-plotly.js": "^1.0.4"
  },
  "browserify": { 
    "transform": [ "plotly" ] 
  }
```

in my webpack.conf
```
  node: {
    fs: "empty"
  },
  module: {
    rules: [{
      test: /\.jsx?$/,
      use: ['babel-loader'],
      include: path.join(__dirname, 'src')
    }],
    loaders: [{
      test: /node_modules.*\.js$/,
      loader: 'ify-loader'
    }]
  }
```

it still gives my an error like this:
`browser.js:2 Uncaught Error: It appears that you're using glslify in browserify without its transform applied. Make sure that you've set up glslify as a source transform`

**Comment by bpostlethwaite** [comment]
I believe this configuration is known to work with plotly.js 
```
https://github.com/rreusser/plotly-webpack/blob/master/webpack.config.js
```
which is a link from this section https://github.com/plotly/plotly.js#building-plotlyjs-with-webpack

I wonder if that loader regex is too restrictive? If you remove the `node_modules` path does it change anything?


We will likely be adding a webpack example in this repo or using webpack to build the distribution some point soon. It may be a few days but we will get back to this issue once recovering from the holiday season. Let us know if anything changes, thanks!

**Comment by KIC** [comment]
Hmm it seems to be a bit bitchy to find the correct configuration if you also use other modules. However I reverted the regex to `\.js$` but I have also added the devDepedency `"envify": "^4.1.0"`. Now at least it builds and does not crash. But I can not see the chart. A wrorking webpack example would be cool. Nowadays every tutorial just uses webpack and drags you in :-)

**Comment by KIC** [comment]
ok this setup seem to work, I think one can close this issue. But an example would stil be greeeaat! :)

package.json:

```
  "devDependencies": {
    "babel-core": "^6.9.1",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "webpack": "^3.5.5",
    "webpack-dev-server": "^2.7.1",
    "html-webpack-plugin": "^2.30.1",
    "ify-loader": "^1.1.0",
    "transform-loader": "^0.2.4",
    "envify": "^4.1.0"
  },
  "dependencies": {
    "mobx": "^3.0.0",
    "mobx-react": "^4.1.0",
    "mobx-react-devtools": "^4.2.11",
    "plotly.js": "^1.31.2",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-plotly.js": "^1.0.4"
  }
```

note that in the package.json I removed the broserfiy things. In the webpack donf the fs emtpy is needed as well as the follwoing module settings:

```
  node: {
    fs: "empty"
  },
  module: {
    rules: [{
      test: /\.jsx?$/,
      use: ['babel-loader'],
      include: path.join(__dirname, 'src')
    },
    {
      test: /\.js$/,
      use: 'ify-loader',
    }]
  }
```

**Comment by rreusser** [comment]
@KIC I'd put it on ice for a while playing with configuration and which combination of modules to use, but I've restored the readme in [my worked example](https://github.com/rreusser/plotly-webpack). (in particular, bundle-collapser for browserify turned out to have a pretty rare de-duping bug). It walks through some possibilities on configuring and tuning to get things down to the minimum size. @bpostlethwaite glad to fix, transfer, or do whatever with it to help communicate an example. 👍

**Comment by bpostlethwaite** [comment]
Cool thanks @rreusser. Tour example repo is a useful resource for plotly.js in general so we can simply copy parts of it into this repo and alter it to use `react-plotly.js` specifically. You can't have enough simple working "get up and running" examples.

@nicolaskruchten had an idea to start producing plotly.js bundles that already have the `glsify` transform applied. I think we will explore that avenue in early 2018 as well. Having to use `ify-loader` is a workaround not a solution.

**Comment by bpostlethwaite** [comment]
reopening until @nicolaskruchten has chance to comment

**Comment by nicolaskruchten** [comment]
I'll create a clear, minimal example of getting this library working with Webpack :)

Thanks for showing us what worked for you @KIC !

**Comment by tim-soft** [comment]
@nicolaskruchten did you wind up following though on those points? 

react-plotly in webpack appears to be very finicky

**Comment by nicolaskruchten** [comment]
Check out https://github.com/plotly/plotly-webpack for the up to date webpack guidance
