### ISSUE TITLE
React-plotly.js scatter3d animation/rotation/transition

### ISSUE THREAD

**Issue by mariusailisoaie** [plotly/react-plotly.js#270]
Hello everyone!

I’m using react-plotly.js version ^2.5.1 to create a scatter3d plot and I want to make it rotate/animate/transition continuously. Right now it is static and I can only rotate it manually.

I searched for this on many different websites (plotly, stackoverflow, github, others) and I didn’t find a way to do this. I need a solution for React, not Vanilla JS, please, but if this can be achieved by a combination of React + JS, let me know.

I need to achieve something like this: [scatter3d plot animation/rotation gif](https://i.stack.imgur.com/6ohqm.gif)

Thank you very much and best regards!

**Comment by mariusailisoaie** [comment]
I managed to do this.

**Comment by Hamik25** [comment]
[mariusailisoaie](https://github.com/mariusailisoaie) please can you share how you have solved this issue I have the same issue?
