### ISSUE TITLE
"Uncaught ReferenceError: self is not defined" when trying to import using require

### ISSUE THREAD

**Issue by phelps-sg** [plotly/react-plotly.js#272]
I get the error in the node repl when trying to import react-plotly using require.  In the browser, the call to `require('react-plotly.js')` returns undefined, though I don't any exception in the console.

~~~
Welcome to Node.js v16.13.1.
Type ".help" for more information.
> const {Plot} = require('react-plotly.js');
Uncaught ReferenceError: self is not defined
    at Object.58 (/home/sphelps/tmp/test/node_modules/plotly.js/dist/plotly.js:9084:9)
    at o (/home/sphelps/tmp/test/node_modules/plotly.js/dist/plotly.js:7:631)
    at /home/sphelps/tmp/test/node_modules/plotly.js/dist/plotly.js:7:682
    at Object.503.../constants/numerical (/home/sphelps/tmp/test/node_modules/plotly.js/dist/plotly.js:128735:10)
    at o (/home/sphelps/tmp/test/node_modules/plotly.js/dist/plotly.js:7:631)
    at /home/sphelps/tmp/test/node_modules/plotly.js/dist/plotly.js:7:682
    at Object.1.../src/lib (/home/sphelps/tmp/test/node_modules/plotly.js/dist/plotly.js:10:11)
    at o (/home/sphelps/tmp/test/node_modules/plotly.js/dist/plotly.js:7:631)
~~~

I am using the following dependencies:

~~~js
 "dependencies": {
    "plotly.js": "^2.8.3",
    "react-plotly.js": "^2.5.1"
  }
~~~

Any suggestions as to what I am doing wrong?

**Comment by phelps-sg** [comment]
I resolved this by using the following:

~~~javascript
const Plot = require('react-plotly.js').default;
~~~

**Comment by apinanyogaratnam** [comment]
how would this work in next.js I'm getting the same issue but Im using es6 imports. 

`import Plot from 'react-plotly.js';`

spits out the same issue

**Comment by Nostin** [comment]
So is that the end of plotly then?

**Comment by jacobq** [comment]
Are we talking about Node.js's `require` function for loading CJS modules? In that case, code like this is a problem:
https://github.com/plotly/d3/blob/6bb40cd42f6479be84efda3e50c8444b50d5905d/src/xhr/xhr.js#L24
because it relies on the global [`self`](https://developer.mozilla.org/en-US/docs/Web/API/Window/self), which exists in browsers but not in node.js environments. Similar problems crop up for [`document`](https://developer.mozilla.org/en-US/docs/Web/API/Document), [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser), etc..

<details><summary>require(`plotly.js`) fails in Node.js normally</summary>

```
$ node
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> require('plotly.js/package.json').version
'2.12.0'
> require('plotly.js')
Uncaught ReferenceError: self is not defined
    at Object.<anonymous> (C:\Users\user\tmp-project\node_modules\plotly.js\node_modules\@plotly\d3\d3.js:6827:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
> require('plotly.js/dist/plotly-basic')
Uncaught ReferenceError: self is not defined
    at Object.11 (C:\Users\user\tmp-project\node_modules\plotly.js\dist\plotly-basic.js:6964:9)
    at o (C:\Users\user\tmp-project\node_modules\plotly.js\dist\plotly-basic.js:7:631)
    at C:\Users\user\tmp-project\node_modules\plotly.js\dist\plotly-basic.js:7:682
    at Object.232.../constants/numerical (C:\Users\user\tmp-project\node_modules\plotly.js\dist\plotly-basic.js:43656:10)
    at o (C:\Users\user\tmp-project\node_modules\plotly.js\dist\plotly-basic.js:7:631)
    at C:\Users\user\tmp-project\node_modules\plotly.js\dist\plotly-basic.js:7:682
    at Object.1.../src/lib (C:\Users\user\tmp-project\node_modules\plotly.js\dist\plotly-basic.js:10:11)
    at o (C:\Users\user\tmp-project\node_modules\plotly.js\dist\plotly-basic.js:7:631)
```

</details>

Attempting to work around this with [polyfills](https://javascript.info/polyfills) ([JSDOM](https://www.npmjs.com/package/jsdom) & [canvas](https://github.com/Automattic/node-canvas)) almost works
<details><summary>So close</summary>

```
$ npm install jsdom canvas
(snip)
$ node
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> var { JSDOM } = require('jsdom');
undefined
> var { window } = new JSDOM('<!DOCTYPE html><html><head></head><body><p>fake page</p></body></html>');
undefined
> var document = window.document;
undefined
> globalThis.self = window;
(snip)
> globalThis.DOMParser = window.DOMParser
[class DOMParser]
> require('plotly.js/dist/plotly-basic'); // Doesn't throw; yay!!
(snip)
> require('plotly.js') // Still have more work to do
Uncaught ReferenceError: getComputedStyle is not defined
    at Object.<anonymous> (C:\Users\user\tmp-project\node_modules\gl-text\dist.js:30:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

```

</details>

See also https://github.com/plotly/plotly.js/issues?q=is%3Aissue+is%3Aopen+node

**Comment by ext-rahul** [comment]
> how would this work in next.js with typescript I'm getting the same issue but Im using es6 imports.
> 
> `import Plot from 'react-plotly.js';`
> 
> spits out the same issue

Getting the same issue. Any workaround here?

**Comment by just-Bri** [comment]
Seeing this error as well, tried both import methods and no luck.

**Comment by ext-rahul** [comment]
> > how would this work in next.js with typescript I'm getting the same issue but Im using es6 imports.
> > `import Plot from 'react-plotly.js';`
> > spits out the same issue
> 
> Getting the same issue. Any workaround here?

It worked after dynamically importing the component(which conatins plotly import) without ssr.

```
import dynamic from 'next/dynamic';
const PlotlyGraph = dynamic(
    () =>
        import(
            '../graphs/graph.component'
        ),
    {
        ssr: false,
        loading: () => <>Loading...</>,
    },
);
```

**Comment by seilkhanovk** [comment]
> > > how would this work in next.js with typescript I'm getting the same issue but Im using es6 imports.
> > > `import Plot from 'react-plotly.js';`
> > > spits out the same issue
> > 
> > 
> > Getting the same issue. Any workaround here?
> 
> It worked after dynamically importing the component(which conatins plotly import) without ssr.
> 
> ```
> import dynamic from 'next/dynamic';
> const PlotlyGraph = dynamic(
>     () =>
>         import(
>             '../graphs/graph.component'
>         ),
>     {
>         ssr: false,
>         loading: () => <>Loading...</>,
>     },
> );
> ```

Have you managed to build the application using this approach i.e. to run next build?

**Comment by ryan-williams** [comment]
This resolved it for me:
```diff
-import Plot from "react-plotly.js"
+const Plot = dynamic(() => import("react-plotly.js"), { ssr: false, })
```

My understanding is that you basically need to skip `react-plotly.js` import/execution during SSR.

Additionally, I'm using Typescript in next.js, and referencing the `PlotParams` type; that import seems to still work directly from the package:

```diff
-import Plot, {PlotParams} from "react-plotly.js"
+const Plot = dynamic(() => import("react-plotly.js"), { ssr: false, })
+import {PlotParams} from 'react-plotly.js';
```

**Comment by peterb0yd** [comment]
If you're looking for a way to solve this in Remix JS, use lazy loading to load your component and `Suspense` from React 18 with a fallback component as shown here:
```
// index.tsx

import { Suspense, lazy } from "react";

let MyPlot = lazy(() => import("~/components/plot"));

export default function Index() {
  return (
    <div>
      <Suspense fallback={<p>LOADING</p>}>
        <MyPlot />
      </Suspense>
    </div>
  );
}
```

```
// /components/plot.tsx

import Plot from 'react-plotly.js';

export default () => {
  return (
    <Plot
      data={[
        {
          x: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
          y: [1, 2, 3, 6, 5, 7, 12, 15, 17, 25, 50],
          type: 'scatter',
          mode: 'lines',
          marker: {color: 'red'},
        },
        {
          x: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
          y: [1, 1, 1.5, 2, 3, 2.5, 4, 4, 5, 3],
          type: 'scatter',
          mode: 'lines',
          marker: {color: 'blue'},
        },
      ]}
      layout={ {width: 520, height: 440, title: `My Cool Graph` } }
    />
  );
}
```

Hope that helps.

**Comment by Disorrder** [comment]
@peterb0yd I've found a better solution. Just suffix component's file name with `.client.tsx`

**Comment by iaverypadberg** [comment]
> This resolved it for me, in next.js:
> 
> ```diff
> -import Plot from "react-plotly.js"
> +import dynamic from "next/dynamic";
> +const Plot = dynamic(() => import("react-plotly.js"), { ssr: false, })
> ```
> 
> My understanding is that you basically need to skip `react-plotly.js` import/execution during SSR.
> 
> Additionally, I'm using Typescript in next.js, and referencing the `PlotParams` type; that import seems to still work directly from the package:
> 
> ```diff
> -import Plot, {PlotParams} from "react-plotly.js"
> +import dynamic from "next/dynamic";
> +const Plot = dynamic(() => import("react-plotly.js"), { ssr: false, })
> +import {PlotParams} from 'react-plotly.js';
> ```

I had to add a ``` 'use client' ``` to the top of the page for this solution to work

**Comment by vincerubinetti** [comment]
Using Astro and had the same issue, even when not using this library and just using `plotly.js` library.

I had to make my own React component for it like this:

```
import { useEffect, useRef } from "react";
import Plotly from "plotly.js-dist";

const Plot = ({ data, layout }) => {
  const ref = useRef();

  useEffect(() => {
    if (!ref.current) return;
    Plotly.newPlot(ref.current, { data, layout });
  }, []);

  return <div ref={ref}></div>;
};

export default Plot;
```

And use it only on the client, like `<Plot client:only="react">`.

I guess the authors of Plotly didn't design it for any kind of server side rendering.

**Comment by manu-one** [comment]
`
import dynamic from "next/dynamic";
const Plot = dynamic(() => import("react-plotly.js"), { ssr: false, })
`

`      
    <Plot
            config={{
              modeBarButtonsToAdd: [
                {
                  name: "nBtn",
                  icon: Icons.camera,
                  click: async (gd) => {
                    console.log("New mode button pressed");
                  },
                  title: "New mode button",
                },
              ],
            }}
            data={plotlyData.data}
            layout={{
              ...plotlyData.layout,
            }}
        />
`

Back to square one with the same issue if we try to add any new dynamic components to the imported plot. Not sure how to solve this issue.

Same error during build time.
