### ISSUE TITLE
How do we add variables to the hoverTemplate option like we can in python. 

### ISSUE THREAD

**Issue by AyoCodess** [plotly/react-plotly.js#274]
For example, im using reactQuery:

i'm trying to format the hover-template with variables. i also want to use functions to format dates within the hover template, but im having no luck with any of it using react. 
 
```
  select: (data) => {
        return data.data.map((d, i) => ({
          x: d.x,
          y: d.y,
          text: 'hello',
          type: 'scatter',
          mode: 'lines',
          marker: { color: eyes[i].values.color },
          line: {
            width: 3,
          },
          name: `${eyeNames[i]} Eye`,
          showlegend: false,
          hovertemplate:
            '<b> %{text}</b><br>' +
            '<i>Risk</i>: %{y:.2f}%' +
            '<br><i>Year</i>: %{x:.2f}',
        }));
      },
    }
  );
  ```
Is there a way to handle this? the JS documentation doesn't apply to react in this case. I looked at the python documentation too but no hints. 
```
        text: 'hello',
        '<b> %{text}</b>'
```
        
![Screenshot 2022-01-31 at 17 07 07](https://user-images.githubusercontent.com/72066389/151766410-55fed690-9047-4532-9fa7-8a89e404540a.png)

**Comment by AyoCodess** [comment]
Can anyone help?

**Comment by govind-ootb** [comment]
@AyoCodess 
Have you tried using the back-ticks, just like you have used for `name`?
I know that it works for `texttemplate`, but not sure if it will work for `hovertemplate`.

**Comment by govindthakur25** [comment]
@AyoCodess
Have you tried using the back-ticks, just like you have used for name?
I know that it works for texttemplate, but not sure if it will work for hovertemplate.

**Comment by AyoCodess** [comment]
> hovertemplate: `<b> %{d.text}</b><br>
>             <i>Risk</i>: %{y:.2f}%<br>
>             <i>Year</i>: %{x:.2f}`,

Thank you. i eventually worked this out. the biggest issue i'm having now is being able to format my x and y graph points.

for graph points are all floating point numbers and i want covert them to percentages from within the hovertemplate. 

but im still struggling with this, tis is what i have so far...

``` text: `${d.y * 100}`,
        hovertemplate: `<b> {%{text}}</b><br>
            <i>Risk</i>: %{y:.2f}%<br>
            <i>Year</i>: %{x:.2f}`,```

**Comment by AyoCodess** [comment]
this was solved by using 'customdata'

``` 
select: (data) => {
      return data.data.map((d, i) => ({
        x: d.x,
        y: d.y,
        type: 'scatter',
        mode: 'lines',
        marker: { color: datasets[i].color },
        line: {
          width: 3,
        },
        showlegend: false,
        customdata: 
          d.x.map((x) => {
            const years = Math.floor(x);
            const months = Math.floor(12 * (x % 1));
            if (years === 0) return `${months}m`;
            if (months === 0) return `${years}y`;
            return `${years}y ${months}m`;
          }),
        ```
