### ISSUE TITLE
fit property doc is wrong?

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js#30]
The `fit` property documentation appears to be wrong in that any existing `layout.width` or `layout.height` is not ignored... Need to decide if the docs should be updated to match the implementation or vice versa.

**Comment by stephanemombuleau** [comment]
fit doesn't seem to work properly at all, wether height&width are set or not. It creates a 700x450 SVG on my side...

**Comment by nicolaskruchten** [comment]
I'll try to put together a simple example of it working, because it does fit to the containing element, but it's quite sensitive to the CSS around it it seems.

**Comment by nicolaskruchten** [comment]
I've improved the documentation and marked this prop as 'deprecated' for now :)
