### ISSUE TITLE
How do I configure spikedistance?

### ISSUE THREAD

**Issue by sentanos** [plotly/react-plotly.js#321]
The plotly.js [docs](https://plotly.com/javascript/reference/layout/#layout-spikedistance) have `spikedistance` which should be under `layout` but I don't see any reference to this in the React library

**Comment by sentanos** [comment]
This is probably an issue with the types library, not this one

**Comment by RBLXUSER2008** [comment]
Howdy there, terribly sorry to bother you but I have somehting very crucial to talk to a member of RBLX Staff about, I did some background searching and saw that you currently work at RBLX I have been making attempts to contact someone who works at the platform but it is very difficult, I have something to discuss regarding vulnerabilities and safety of the site as there are many issues going on behind the scenes, but ive been unable to successfully contact anyone who genuinely cares. Please could you get back to me if possible with means to speak to you privately, it'd be much appreciated thank you.
