### ISSUE TITLE
Depreciated in favor of Angular?

### ISSUE THREAD

**Issue by jacksongoode** [plotly/react-plotly.js#322]
Hi, I'm just wondering if this plugin will see any more development? I see the Angular version is getting more frequent updates.

**Comment by alexcjohnson** [comment]
Are there updates it needs? For the most part this component is stable, most of the updates are on the plotly.js side but this package doesn't generally need updating to work with a new plotly.js version. If the hooks PR is finished we'll gladly merge and released that, and I see a couple of other small PRs we could review and release along with that.

**Comment by jacksongoode** [comment]
Thanks for your response. Yes I was mostly eyeing the hooks PR and the package import PR.
