### ISSUE TITLE
Update plotly.js to include the latest version

### ISSUE THREAD

**Issue by msimoni18** [plotly/react-plotly.js#323]
Please update to ``plotly.js: 2.24.1`` so we can use features like [#6535](https://github.com/plotly/plotly.js/pull/6535). I tried doing it myself, but when I tried to push my branch to the remote repo, I received a permission denied message.

**Comment by alexcjohnson** [comment]
plotly.js is a peer dependency, this component should work just fine with whatever version you install.

Glad to hear you're excited about multiple legends - we are too!!!
