### ISSUE TITLE
React plotly components website currently giving certificate error

### ISSUE THREAD

**Issue by mungojam** [plotly/react-plotly.js#37]
[https://react.plot.ly/](https://react.plot.ly/) is currently not loading in chrome. I got this at work and at home on completely different setups:

> react.plot.ly normally uses encryption to protect your information. When Google Chrome tried to connect to react.plot.ly this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be react.plot.ly, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.
> 
> You cannot visit react.plot.ly right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by nicolaskruchten** [comment]
Thanks for letting us know! /cc @jackparmer

**Comment by jackparmer** [comment]
Whoops! I'm updating that page with a new URL... will update the README and
close this when it's finished.

**Comment by jackparmer** [comment]
Thanks @mungojam - Fixed in https://github.com/plotly/react-plotly.js/commit/a2a147685578e0a34a34a098db7e2417d9f783f6

https://plot.ly/products/react/
