### ISSUE TITLE
useResizeHandler no longer works correctly

### ISSUE THREAD

**Issue by swiperii** [plotly/react-plotly.js#41]
After latest plotly.js update (1.34), plots with useResizeHandler prop are no longer resized with the surrounding div. They may still resize correctly when e.g. window size is changed. 

See [CodePen example](https://codepen.io/swiperii/pen/KQyrgd?editors=0010)

Seems to be related to the use of the Plotly.react method, since it still seems to work correctly when I use my own Plotly.react implementation.

**Comment by nicolaskruchten** [comment]
Interesting. How does your implementation work?

`useResizeHandler` just attached to the `window` resize event, so I wouldn't expect it to fire when you resize the containing `div` in any case...

**Comment by swiperii** [comment]
I can provide the implementation later if you are interested. But it also did work with previous versions of plotly.js. When using `<script crossorigin src="https://cdn.plot.ly/plotly-1.33.1.min.js">` instead of  `plotly-latest.min.js` in the CodePen example, the plot is resized with the div.

**Comment by nicolaskruchten** [comment]
Yes, I can see what you mean. If I just set `Plotly.react = undefined;` at the top of your script I can see the old behaviour. 

@alexcjohnson any thoughts here as to whether this is the desired behaviour for `Plotly.react`?

**Comment by alexcjohnson** [comment]
Ah interesting - yes, height and width (can) depend on state outside the `Plotly.newPlot` (or `Plotly.react`) arguments. They're the only attributes for which this is true, AFAIK. We have [special handling](https://github.com/plotly/plotly.js/blob/ce5bc971770daaf3ed60d374f23a8af1bb61fe0b/src/plot_api/plot_api.js#L2053-L2064) for this in `Plotly.relayout`, we should just carry the same behavior over to `Plotly.react`. I'll make an issue for it. Thanks for bringing this up @swiperii

**Comment by nicolaskruchten** [comment]
This is fixed with plotly.js 1.35.0 :) https://github.com/plotly/plotly.js/releases/tag/v1.35.0

**Comment by esmejia277** [comment]
> This is fixed with plotly.js 1.35.0 :) https://github.com/plotly/plotly.js/releases/tag/v1.35.0

I just install this version and it work, thanks a lot

**Comment by trusktr** [comment]
Can you please fix this proper, and use `ResizeObserver` on a `width:100%;height:100%` internal container when `autosize` is `true` to detect size changes?

https://github.com/plotly/plotly.js/search?q=ResizeObserver
