### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by swiperii** [plotly/react-plotly.js#42]
I get the following error in console: 

> (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

Not sure what causes it, but it seems to be related to dynamic data updates. It can be seen in this example: [CodePen](https://codepen.io/swiperii/pen/wyPEBW?editors=0010). Click "Add data" and watch console.

**Comment by nicolaskruchten** [comment]
Thanks for the helpful CodePen examples! I'll try to track this one down shortly :)

**Comment by nicolaskruchten** [comment]
This should be fixed in version 1.4.0 on NPM now. Thanks again for the bug report :)
