### ISSUE TITLE
Axes not redrawing after layout change

### ISSUE THREAD

**Issue by igorpejic** [plotly/react-plotly.js#45]
After migrating to plotly.js@**1.34.0** and react-plotly@**1.4.0** axes are not being redrawn after changing the number of axes in ```layout```.

### Before:
![screenshot](https://user-images.githubusercontent.com/6241267/36492414-5ce6e7c4-172d-11e8-8c2a-f53ebc11e4c3.png)
### After:
![screenshot](https://user-images.githubusercontent.com/6241267/36492455-7ab72ea8-172d-11e8-804f-e5b6c7937796.png)

https://codepen.io/igorpejic/pen/yvjxMY?editors=1010

I have tried adding the datarevision argument, but it didn't help.

(Let me know if this is a proper fit for react-plotly.js or I should post it to plotly.js)

**Comment by nicolaskruchten** [comment]
This is the right place, and thanks for the easy to see demo! I'll try to get a fix or answer for you this week.

**Comment by nicolaskruchten** [comment]
@alexcjohnson is this one of those cases where `Plotly.react` needs a bit of extra help to clean up axes?

**Comment by alexcjohnson** [comment]
Looks like a plotly.js bug, it's not specific to `Plotly.react`, I can get this to happen with `Plotly.deleteTraces` too:

```js
Plotly.newPlot(gd,
    [{y: [1,2,3]}, {y: [10, 30, 20], yaxis: 'y2'}],
    {yaxis2: {side: 'right', overlaying: 'y'}}
);
Plotly.deleteTraces(gd, [1]);
```

I'll make a new issue for it over there.

**Comment by igorpejic** [comment]
I have temporarily solved the issue by manually checking if datarevision has changed in react-plotly.js in my own fork.

https://github.com/plotly/react-plotly.js/compare/master...igorpejic:master#diff-d4165b1e3527a04dd7e9d370e18c2a1a


After some investigation in plotly.js I assume the bug was introduced by: https://github.com/plotly/plotly.js/pull/2341 and https://github.com/plotly/plotly.js/pull/2227

Specifically commits like this which are connected with different restyle logic: https://github.com/plotly/plotly.js/commit/aab4f11ff1200b8a58d287a03670034354a6b060

**Comment by nicolaskruchten** [comment]
This is fixed with the latest version of plotly.js https://github.com/plotly/plotly.js/releases/tag/v1.35.0
