### ISSUE TITLE
Axis showline rerender bug

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js#53]
Toggling `showline` from true to false doesn't result in the line going away. Example: https://codepen.io/nicolaskruchten/pen/OQaYWv?editors=1010

possibly related to #45? /cc @alexcjohnson

**Comment by alexcjohnson** [comment]
This is a plotly.js bug, would you mind filing it over there and I'll take care of it? Happens with `Plotly.relayout` too, not just `Plotly.react`. Similar to #45 but I think it has a distinct cause.

**Comment by nicolaskruchten** [comment]
Sure, I'll file a bug over there. I think this is a recent regression...

**Comment by nicolaskruchten** [comment]
Will need to import code from https://github.com/plotly/streambed/blob/master/shelly/webapp/static/webapp/src/workspace/schemas/Annotations.js#L14

**Comment by nicolaskruchten** [comment]
Fixed with https://github.com/plotly/plotly.js/releases/tag/v1.35.0
