### ISSUE TITLE
Updates to pie chart data require click on legend to update properly

### ISSUE THREAD

**Issue by snazzypants** [plotly/react-plotly.js#62]
First render works fine. When I update the data prop, the chart changes, but incorrectly - it shows just one label/group with 100% portion of the pie. At this point, if I click on the legend to toggle the trace, the plot updates and works correctly.  Any subsequent data prop updates will generate the same behavior; clicking on the legend always fixes it.

I have the same chart in bar chart form, responding to the same data with changes at the same time. Bar chart updates OK.  Using `react-plotly.js 1.7.0` and `plotly.js 1.35.2`, loaded via script tag. 

Prior to today, I had been running `plotly.js 1.31.2` - it was working on that version of plotly.js.   The project I am currently working on is a re-write of a jquery app to a react app. I tested the same pie chart on the jquery app with `plotly.js 1.35.2` and it was able to interact fine - so it seems that this problem is an interaction between 1.35.2 and react-plotly.js

**Comment by nicolaskruchten** [comment]
There was indeed a big change in the interaction between `react-plotly.js` and `plotly.js` when the `Plotly.react()` method was implemented in `plotly.js@1.34.0`, so you may be experiencing issues from that. Can you post a CodePen which demonstrates the issue you're seeing please?

**Comment by snazzypants** [comment]
Thanks - https://codepen.io/thecrusher/pen/JLYXed

**Comment by nicolaskruchten** [comment]
Thanks for this, it's quite clear :)

@alexcjohnson this seems like `Plotly.react` issue to me...

**Comment by alexcjohnson** [comment]
Huh, seems like a transform issue. I'll make an issue on the plotly.js side, but the good news is as of v1.32 you don't need to aggregate pies yourself, it's [built into the pie trace](https://github.com/plotly/plotly.js/pull/2117)

Here's simplified to pure plotly.js with transform, shows the error:
https://codepen.io/alexcjohnson/pen/xWwrXR?editors=0010

Here's the same with no transform, works as expected:
https://codepen.io/alexcjohnson/pen/BroZNx?editors=0010

**Comment by alexcjohnson** [comment]
update: it's a problem with transforms *and* `Plotly.react` - switch to `restyle` and it works correctly again. @snazzypants thanks for the report!

https://codepen.io/alexcjohnson/pen/geaRej?editors=0010

**Comment by snazzypants** [comment]
@alexcjohnson  Thanks! Easy enough to just not use the transform!

**Comment by antoinerg** [comment]
The [Codepen](https://codepen.io/thecrusher/pen/JLYXed) provided by @snazzypants now works as expected using the latest version of plotly.js :tada:
