### ISSUE TITLE
How to use the layout.autosize?

### ISSUE THREAD

**Issue by lucas-viewup** [plotly/react-plotly.js#76]
Good day, I'm having problem with the attribute autosize of layout property, I set to true but is not working as the docs says:

> Note: To make a plot responsive, i.e. to fill its containing element and resize when the window is resized, use style or className to set the dimensions of the element (i.e. using width: 100%; height: 100% or some similar values) and set useResizeHandler to true while setting layout.autosize to true and leaving layout.height and layout.width undefined. This will implement the behaviour documented here: https://plot.ly/javascript/responsive-fluid-layout/

What I want is have a container that defines  the area of the charts like I highlighted in this image:
![react-ploty-autoresize](https://user-images.githubusercontent.com/28161720/39528719-3ea1ed2c-4dfb-11e8-981a-7402fc2f430a.png)

**Comment by lucas-viewup** [comment]
Ok, I did solve this using className in plot component and setting ```height: 100%``` and ```width: 100%```, maybe would be good have already a css inline when you set autosize, thats the expected behaviour when autosize is enabled.

**Comment by lucas-viewup** [comment]
I reopened this issue because when the page is loaded, the charts fills perfectly in the screen, but when I resize the window, It begins to scroll horizontally. I am using create-react-app just to test this and to help if we need to make a specific test.

**Comment by athaax** [comment]
Hey, I think I'm running into this issue too. Maybe I don't understand the expected behavior, but what I'm looking for is the chart width to be responsive to its parent. @lucas-viewup did you land on a solution that worked for you?

**Comment by LimmaPaulus** [comment]
I also had problems with responsive width behavior. Solution suggested in docs didn't worked when used with [FlexLayout-docking manager](https://github.com/caplin/FlexLayout). I succeeded to solve the problem with [react-sizeme](https://github.com/ctrlplusb/react-sizeme)

```
const PlotContainer = (props) => {
    return <Plot data={...}
                 layout={{
                     autosize: false,
                     width: this.props.size.width
                 }}/>
};

export default sizeMe()(PlotContainer)

```

**Comment by nicolaskruchten** [comment]
This CodePen shows how to follow the existing documentation in the Readme: https://codepen.io/nicolaskruchten/pen/ERgBZX

The documentation states:

> To make a plot responsive, i.e. to fill its containing element and resize when the window is resized, use `style` or `className` to set the dimensions of the element (i.e. using `width: 100%; height: 100%` or some similar values) and set `useResizeHandler` to `true` while setting `layout.autosize` to `true` and leaving `layout.height` and `layout.width` undefined. This will implement the behaviour documented here: https://plot.ly/javascript/responsive-fluid-layout/

So that's exactly what this CodePen does, with the only caveat being that in order to demo a full-screen version I set CSS `width/height` on the parent div and the document itself also.

**Comment by LimmaPaulus** [comment]
Yes, but as documentation states, with useResizeHandler=true plot resizes only when whole window is resized because it reacts only to window.onresize-event. This is not enough if you have more dynamic layout.

**Comment by nicolaskruchten** [comment]
That's true. What would be a good way forward? A new prop that registers a callback or something to call resize for other events than window.resize?

**Comment by mohammedzamakhan** [comment]
Any updates?

**Comment by nicolaskruchten** [comment]
No updates at this time as I haven't gotten a lot of feedback from users about what would help here :)

**Comment by mohammedzamakhan** [comment]
I would suggest a method in the component, that can be fired from the Parent whenever the resize event occurs,

```
class Parent extends Component {
  constructor(props) {
    super(props);
    this.child = React.createRef();
  }

  onClick = () => {
    this.child.current.getAlert();
  };

  render() {
    return (
      <div>
        <Child ref={this.child} />
        <button onClick={this.onClick}>Click</button>
      </div>
    );
  }
}

class Child extends Component {
  getAlert() {
    alert('getAlert from Child');
  }

  render() {
    return <h1>Hello</h1>;
  }
}

ReactDOM.render(<Parent />, document.getElementById('root'));
```

**Comment by mohammedzamakhan** [comment]
I actually was able to implement it without any changes in the library
https://codesandbox.io/s/18lxjp9ywl

I also have to have this implemented in my app, and see if this solutions covers all my requirements.

**Comment by mohammedzamakhan** [comment]
@ArcticTee Sorry I deleted that codesandbox example,

here is a working example https://codesandbox.io/s/35loxpjmq

**Comment by mcgodes** [comment]
Yessssss @mohammedzamakhan thank you I couldn't find this anywhere

**Comment by greysonevins** [comment]
Updated @mohammedzamakhan 's solution to new functional component standards https://codesandbox.io/s/bold-shadow-tcgkn

**Comment by CKanishka** [comment]
@mohammedzamakhan Thanks a lot, your solution helped

**Comment by richardoptibrium** [comment]
Great solutions, I'm still at a loss on how to do it though in a div when the div resizes. I have been using react-resize-detector with other chart libraries but not sure how I could _force_ a redraw of a plotly chart?

**Comment by richardoptibrium** [comment]
I tried this but it loses the bars as I'm not resubmitting the 'type' information. This also seems clumsy and clunky.


import Plot from 'react-plotly.js';
import Plotly from 'plotly.js';

export class Visualisation extends React.Component {

	handleResize = () => {
		console.log("handleResize");
		const graphDiv = document.getElementById('histogramChart');
		const data = [
			{
				x: [1, 2, 3],
				y: [2, 6, 3],
				type: 'scatter',
				mode: 'lines+markers',
				marker: { color: 'red' },
			}
		];
		const layout = {
			title: 'A Fancy Plot',
			autosize: true,
		};
		Plotly.react(graphDiv, data, layout);
	};


	render() {
		const { chartType } = this.state;
		return (
			<div id='visualisation'>
				<div className='visualisation-chart' id='histogramChart' style={{ display: `${chartType === 'histogram' ? 'block' : 'none'}` }} >
					<Plot
						className='visualisation-plot'
						useResizeHandler
						data={[
							{
								x: [1, 2, 3],
								y: [2, 6, 3],
								type: 'scatter',
								mode: 'lines+markers',
								marker: { color: 'red' },
							},
							{ type: 'bar', x: [1, 2, 3], y: [2, 5, 3] },
						]}
						layout={{
							// width: 320,
							// height: 240,
							title: 'A Fancy Plot',
							autosize: true,
						}}
					/>
				</div>

**Comment by AmitPoojary** [comment]
On div resize, you can achieve by 

import Plot from 'react-plotly.js';
const plotRef = useRef<any>(null);

const resizeLayout = () => {
    plotRef.current.resizeHandler();
  };

<Plot ref={plotRef} onRelayout={resizeLayout} useResizeHandler={true}
         data={[ { z: data, type: 'surface' } ]} config={{ responsive: true }}
         layout={{ autosize: true }}
 />

**Comment by KiwiKilian** [comment]
@AmitPoojary while your solution works, it's an endless loop, because `resizeHandler` triggers `onRelayout` again.

Here is our custom `Plot` component without other external dependencies. The `Plot` is just wrapped with a div with a `ResizeObserver`, which calls the `resizeHandler`:

```tsx
import Plotly from 'plotly.js';
import createPlotlyComponent from 'react-plotly.js/factory';
import { PlotParams } from 'react-plotly.js';
import { useEffect, useRef } from 'react';

// @ts-ignore
Plotly.setPlotConfig({ responsive: true });
export const PlotlyPlot = createPlotlyComponent(Plotly);

export const Plot = ({ ...props }: PlotParams) => {
  const elementRef = useRef(null);
  const plotRef = useRef<any>(null);

  useEffect(() => {
    if (!elementRef.current) {
      return;
    }

    const resizeObserver = new ResizeObserver(() => {
      plotRef.current.resizeHandler();
    });

    resizeObserver.observe(elementRef.current);

    return () => {
      resizeObserver.disconnect();
    };
  }, []);

  return (
    <div ref={elementRef} style={{ width: '100%', height: '100%' }}>
      <PlotlyPlot
        // @ts-ignore
        ref={plotRef}
        useResizeHandler
        {...props}
        layout={{
          autosize: true,
          ...props.layout,
        }}
        style={{
          width: '100%',
          height: '100%',
          ...props.style,
        }}
      />
    </div>
  );
};

```
