### ISSUE TITLE
stop using componentWillUpdate

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/react-plotly.js#77]
Currently we update the plot in [`componentWillUpdate`](https://github.com/plotly/react-plotly.js/blob/881c2c147a53269bea23ddeec6df909b5af1ee83/src/factory.js#L86) - it works, but it's a little weird and this method is [deprecated](https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate).

- Put the conditionals preventing updates into `shouldComponentUpdate`?
- Move the update itself to `componentDidUpdate`
- The chain of events in `componentDidMount` (initial draw) and the update code are a little different, but there may be some opportunity to DRY this up - at least, the `Plotly.newPlot` in the initial draw can safely be turned into `Plotly.react`.

**Comment by dmt0** [comment]
@alexcjohnson if we switch to using `Plotly.react`, would we need to bump plotly.js peer dependency which is currently set as: `"plotly.js": ">1.34.0"`

**Comment by alexcjohnson** [comment]
No, v1.34.0 is in fact the version that [introduced `Plotly.react`](https://github.com/plotly/plotly.js/releases/tag/v1.34.0)... which makes sense since the fallback code for missing `Plotly.react` has already been removed.

**Comment by nicolaskruchten** [comment]
Yes merging the logic into DidUpdate and getting rid of newPlot seems like a winner to me
