### ISSUE TITLE
How to use with typescript?

### ISSUE THREAD

**Issue by KosGrillis** [plotly/react-plotly.js#80]
How can I use this product with typescript?

**Comment by BooleT37** [comment]
you can use typings from @types/plotly.js I.e. each trace is `Plotly.Data[]` type, layout is of type `Plotly.Layout`. Initialize as typed variables, then just pass them in props.

**Comment by nicolaskruchten** [comment]
We don't officially support TypeScript so you'll have to either create or find some definition files :)

**Comment by jonfreedman** [comment]
Just for future reference incase TypeScript support is added or to simplify the task of finding a definition file, here's a starting point, PlotParams just needs completing based on https://github.com/plotly/react-plotly.js/#basic-props + https://github.com/plotly/react-plotly.js/#event-handler-props

```typescript
declare module 'react-plotly.js' {
    import * as Plotly from 'plotly.js';
    import {PureComponent} from 'react';

    export interface PlotParams {
        config?: Plotly.Config;
        data: Plotly.Data[];
        layout: Partial<Plotly.Layout>;
        onClickAnnotation?: Plotly.ClickAnnotationEvent;
    }

    export default class Plot extends PureComponent<PlotParams> {
    }
}
```

**Comment by jonfreedman** [comment]
I will create a pull request to add my definitions to DefinatelyTyped once [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27355) is merged.
