### ISSUE TITLE
How can you save the plot as a png file?

### ISSUE THREAD

**Issue by dixyxavier** [plotly/react-plotly.js#81]

**Comment by nicolaskruchten** [comment]
In general to save files to disk you use the 'camera' icon in the modebar. By default this saves to SVG but we've just added a config option to change the default file format to e.g. PNG. It hasn't made its way to the official plotly.js docs yet but the config option is `toImageButtonOptions` and you can set a key like `format: 'png'`.

**Comment by nicolaskruchten** [comment]
Here's the PR in plotly.js https://github.com/plotly/plotly.js/pull/2607/files

**Comment by dixyxavier** [comment]
thank you 👍
