### ISSUE TITLE
Problem rendering values along axes

### ISSUE THREAD

**Issue by RosarioAleCali** [plotly/react-plotly.js#83]
Hello everyone,
I am creating a 3D chart using this library, react, and webpack.
I am facing a rendering issue where the first time I load the web page no values are shown along the x, y, and z-axis.
![newplot](https://user-images.githubusercontent.com/25593250/40673504-f435ae54-633f-11e8-9e98-9c1bee2797a9.png)
However, if I reload the image the values are then shown
![newplot 1](https://user-images.githubusercontent.com/25593250/40673556-178f4a72-6340-11e8-8c3c-2598520cb7cd.png)
Does anyone know how to avoid the first scenario and display the values on the first load.
I am not entirely too sure what the problem may be. Here's my source code, in case you need it:
```
import React from 'react';
import Plot from 'react-plotly.js';
import graphData from '../../public/resources/3d-graph.json';

class Graphs extends React.Component {
    render(){
      return(
        <Plot
            data={[
            {
                type: 'surface',
                x: graphData.x,
                y: graphData.y,
                z: graphData.z
            }
            ]}
            layout={
                {
                    width: 800,
                    height: 600,
                    margin: {
                        l: 50,
                        r: 50,
                        b: 80,
                        t: 90,
                        pad: 4
                    },
                    title: graphData.masterGraph.title,
                    annotations: [{
                        text: graphData.masterGraph.model,
                          font: {
                          size: 14,
                          color: '#444444',
                        },
                        showarrow: false,
                        align: 'center',
                        x: 0.5,
                        y: 1.1,
                        xref: 'paper',
                        yref: 'paper',
                    }],
                    scene: {
                        xaxis: {
                            title: graphData.masterGraph.xAxis,
                            titlefont: {
                              family: 'Courier New, monospace',
                              size: 12,
                              color: '#444444'
                            }
                        },
                        yaxis: {
                            title: graphData.masterGraph.yAxis,
                            titlefont: {
                              family: 'Courier New, monospace',
                              size: 12,
                              color: '#444444'
                            }
                        },
                        zaxis: {
                            title: graphData.masterGraph.zAxis,
                            titlefont: {
                              family: 'Courier New, monospace',
                              size: 12,
                              color: '#444444'
                            }
                        }
                    }
                }
            }
        />
      )
    }
  }

export default Graphs
```
I am using plotly.js (1.38.0), react-plotly.js (2.2.0), react (15.2.1), and webpack 1.12.14.
Please, let me know if you need other info. I know my version of webpack is old but I would prefer not to upgrade as that may break other things.

**Comment by nicolaskruchten** [comment]
This seems related to the react wrapper, so I'll look into it soon. If you could provide a running sample of the problem, i.e. on CodePen by forking [this pen](https://codepen.io/rsreusser/pen/qPgwwJ?editors=1010), that would be really helpful :)

**Comment by RosarioAleCali** [comment]
@nicolaskruchten, thanks for looking into this. [Here](https://codepen.io/rosarioalecali/pen/yENzgz)'s the link to my Pen, this is the first time I am using codepen and it is not showing the graph. So, I don't know if it is supposed to do that or not, since it's not giving me any errors.

**Comment by nicolaskruchten** [comment]
thanks! So if you look in the console there's an error for you to fix, and also you're referencing variables like `graphData.masterGraph.title` which aren't defined there :)

**Comment by RosarioAleCali** [comment]
@nicolaskruchten [Here's](https://codepen.io/rosarioalecali/pen/yENzgz) a version that runs. It looks like it works perfectly here, but please take a look. Maybe there's something wrong with my webpack...

**Comment by nicolaskruchten** [comment]
Hmm OK. Without being able to actually play with a failing test case I'm not sure how I can help... can you push a minimal example to a sample repo for me, including your webpack config, so that I can run a command and observe the broken behaviour on my machine?

**Comment by RosarioAleCali** [comment]
@nicolaskruchten So, yesterday I created a brand new react app (without webpack and it worked perfectly). Then, I tried to add webpack but I had all sorts of other issues making it work and I am still trying to integrate it (Shame on me!). I am pretty positive the problem is with webpack and not plotly. Unfortunately, due to other deadlines I will shift my priorities elsewhere and will come back to this later this summer.

With that being said, I have two questions for you:
1 - Do I leave this issue open until then?
2 - What "webpack environment" do you usually use with Plotly? (i.e. version, webpack.config.js...)

**Comment by nicolaskruchten** [comment]
1. Without being able to replicate it I'm not sure what I can do to help, so I'll eventually close this issue
2. In this project https://github.com/plotly/react-chart-editor we use Webpack 3 and you can see the config etc if you want to try it

**Comment by RosarioAleCali** [comment]
I am closing this issue because I currently do not have the time to work on it. I will keep the community updated in the upcoming months when I will have more time to work on this again. Thanks for the link @nicolaskruchten, I will keep it in mind :)
