### ISSUE TITLE
Display text when hovering on axis name

### ISSUE THREAD

**Issue by RosarioAleCali** [plotly/react-plotly.js#84]
Hello everyone,
I have recently changed the name of x and y-axis using this code snippet:
```
yaxis: {
       title: graph2DLabels.parameterGraphs[0].yAxis,
       titlefont: {
           family: 'Courier New, monospace',
           size: 18,
           color: '#7f7f7f'
     }
}
```
Now, I would really like to display a description when the mouse is over the label name. Does anyone know how to accomplish this? I have tried many different attributes (text, hovertext, ...) but always failed.

**Comment by nicolaskruchten** [comment]
Hi! 

The questions that you're asking are probably best addressed on StackOverflow or at http://community.plot.ly/ as they are plotly.js usage questions rather than specific to this repo's main focus, which is the react-plotly.js wrapper :)
