### ISSUE TITLE
Incompatibility with react-static?

### ISSUE THREAD

**Issue by neilyoung** [plotly/react-plotly.js#89]
While the plotter is working well in SPAs made using react-static https://github.com/nozzle/react-static if run in debug environment, react-static fails to build a productive version of the app. I have filed an issue to react-static, just in case you have an hint.

https://github.com/nozzle/react-static/issues/667

**Comment by nicolaskruchten** [comment]
I must say I've never used `react-static` so I'm not sure how I can help :) if it's working in prod but not debug, it sounds like a `react-static` issue to me?

**Comment by neilyoung** [comment]
@nicolaskruchten Since `document` seems to be a required object, which is not there at  `import` time for react-static (had this with several other modules already: Do you know the proper syntax, how to `require` your library, so that Plot is finally available somewhen?

**Comment by nicolaskruchten** [comment]
In general, this component will not work in non-browser contexts, as `plotly.js` heavily relies on browser APIs...

**Comment by neilyoung** [comment]
I'm running it in a browser, I don't intend to run it on a server.
The problem is, that at load time "document" is not yet defined. Later it is defined. Please refer to this issue and the suggested (and working) solution. https://github.com/nozzle/react-static/issues/288

I tried the same with your lib to no avail.

et Plot
if (typeof document !== 'undefined')  
  Plot = require('../node_modules/react-plotly.js/react-plotly.js').default

In fact, this is not even working in debug mode of react-static, so Plot is all the time undefined.

I need to figure out, how to load your lib with `require` instead of `import`

And pointer welcome.

**Comment by neilyoung** [comment]
@nicolaskruchten OK, have it. Sharing it here for others:

```
let Plot
if (typeof document !== 'undefined') {
  Plot = require('react-plotly.js')
}

```

and conditional render method:

```
{typeof document !== 'undefined' &&
          <Plot
            data={[
              {
                x: this.state.x,
                y: this.state.y,
                z: this.state.z,
                type: 'scatter3d',
                mode: 'bars',
                marker: { color: 'red' },
              }

            ]}
            layout={{ width: 1024, height: 768, title: 'A Fancy Plot' }}
          />}

```
