### ISSUE TITLE
How to modularize react-plotly.js?

### ISSUE THREAD

**Issue by hyperknot** [plotly/react-plotly.js#98]
The main plotly.js repo goes to great length about how to modularise the plotly code and avoid having the huge bundle with Mapbox, etc. 

This library seems to be the official "basis of Plotly's React component suite", yet it's just loading the full plotly.js code. 

https://github.com/plotly/react-plotly.js/blob/6fe45a76d1542419fdbb9379941a631706bcf0a8/src/react-plotly.js#L2

This makes the bundle super big, Webpack super slow, and the minification time skyrocket as the codebase is simply just huge.

Since there is a [whole article](https://plot.ly/javascript/modularizing-monolithic-javascript-projects/) about modularizing plotly, it's strange to me that this lib requires the full build.

What is the best way to use react-plotly with a more minimal plotly bundle?

**Comment by m90** [comment]
@hyperknot You can do what the README is proposing here: https://github.com/plotly/react-plotly.js#customizing-the-plotlyjs-bundle

**Comment by hyperknot** [comment]
Thanks, I see it, actually I figured out the same thing. So I'm just using
a CDN bundle + factory(window.plotly) and it works really well.

**Comment by Rolandisimo** [comment]
Had an issue trying to modularise plotly in the form of react-plotly not being able to find `var _plotly = require('plotly.js/dist/plotly');`. However, I'm using the same approach you did except for the CDN. Instead added `plotly.js-basic-dist` to deps.

```
import Plotly from "plotly.js-basic-dist";
import createPlotlyComponent from "react-plotly.js/factory";
const Plot = createPlotlyComponent(Plotly);
```

Now I get this issue:
<img width="946" alt="screenshot 2018-10-25 at 13 01 42" src="https://user-images.githubusercontent.com/9778368/47493087-2340be00-d857-11e8-8fd2-fc883cc9b6b9.png">


Any ideas?

**Comment by nicolaskruchten** [comment]
Are you importing from `"react-plotly.js"` anywhere? If you're only importing from the factory, you shouldn't see this error, as the only line that refers to that missing file is https://github.com/plotly/react-plotly.js/blob/master/src/react-plotly.js#L2

**Comment by Rolandisimo** [comment]
That's all I'm doing. Note, that I created d.ts files for both imports since there are no typings available yet.

<img width="1385" alt="linechart tsx instagram-bot-react 2018-10-25 16-44-57" src="https://user-images.githubusercontent.com/9778368/47504743-88a3a780-d875-11e8-83c2-b4e2b4b64677.png">

**Comment by nicolaskruchten** [comment]
I'm not sure what more to tell you without seeing a github repo that replicates the problem... if it's not compiling the `react-plotly.js` file, it shouldn't be trying to load `plotly.js/dist/plotly`.

**Comment by Rolandisimo** [comment]
Ok, so I figured out the issue. It was because `react-plotly.js` was being bundled in the 'dependencies`. For my case vendor deps are handled like this:

```
/**
 * Given an array of files this will produce an object which contains the values for the vendor entry point
 */
function makeVendorEntry(config) {
    const packageJson = require('../package.json');
    const vendorDependencies = Object.keys(packageJson['dependencies']);

    const vendorModulesMinusExclusions = vendorDependencies.filter(vendorModule =>
        config.mainModules.indexOf(vendorModule) === -1 && config.modulesToExclude.indexOf(vendorModule) === -1);

    return vendorModulesMinusExclusions;
}

exports.makeVendorEntry = makeVendorEntry;
```

Instead I moved it to the `devDependencies` and it works fine.

**Comment by Rolandisimo** [comment]
Should this issue be closed?

**Comment by lidaof** [comment]
@Rolandisimo , I have this in my devDependency, while this still added 800KB in bundle. is this normal?
Thanks.

**Comment by Rolandisimo** [comment]
@lidaof It all comes down to how you bundle your dependencies. Maybe you're bundling unnecessary modules or/and simply bundling not minimized/not uglified bundles. Check prod bundles and see if you add the same weight. If not customsied, plotly bundles are heavy.

**Comment by lidaof** [comment]
i see, thanks anyways! @Rolandisimo

**Comment by sdpetrides** [comment]
```
npm install react-plotly.js plotly.js-cartesian-dist
```

package.json
```
  "dependencies": {
    ...
    "plotly.js-cartesian-dist": "^1.55.2",
    "react": "^16.8.6",
    "react-plotly.js": "^2.4.0",
    ...
  },
```
In components...
```
import Plotly from "plotly.js-cartesian-dist";
import createPlotlyComponent from "react-plotly.js/factory";

const Plot = createPlotlyComponent(Plotly);
```


Worked for me 👍

**Comment by igorbuts** [comment]
@sdpetrides 
when doing like in your example I got `Uncaught TypeError: Object(...) is not a function`  for line:
```
const Plot = createPlotlyComponent(Plotly);
```

Is it still working for you?
